package eu.luminis.elastic.document;

/**
 * Request to use when inserting a new document, or overwriting an existing document. If you do
 * not provide an <code>id</code>, a POST is used, so an id is generated by elastic. If you do
 * provide an <code>id</code>, a PUT is used and that id is used.
 */
public class IndexRequest extends DocumentRequest {
    private Object entity;

    public IndexRequest() {
    }

    public IndexRequest(String index, String type) {
        super(index, type, null);
    }

    public IndexRequest(String index, String type, String id) {
        super(index, type, id);
    }

    public Object getEntity() {
        return entity;
    }

    public void setEntity(Object entity) {
        this.entity = entity;
    }
}
