package eu.luminis.elastic.document;

/**
 * Request to use when inserting a new document, or overwriting an existing document. If you do
 * not provide an <code>id</code>, a POST is used, so an id is generated by elastic. If you do
 * provide an <code>id</code>, a PUT is used and that id is used.
 */
public class IndexRequest {
    private String index;
    private String type;
    private String id;
    private Object entity;

    public String getIndex() {
        return index;
    }

    public IndexRequest setIndex(String index) {
        this.index = index;
        return this;
    }

    public String getType() {
        return type;
    }

    public IndexRequest setType(String type) {
        this.type = type;
        return this;
    }

    public String getId() {
        return id;
    }

    public IndexRequest setId(String id) {
        this.id = id;
        return this;
    }

    public Object getEntity() {
        return entity;
    }

    public IndexRequest setEntity(Object entity) {
        this.entity = entity;
        return this;
    }

    public static IndexRequest create() {
        return new IndexRequest();
    }
}
